#!/bin/python3

import typer
import os

app = typer.Typer()
path = os.path.expanduser('~/.task/tasks.txt')

class Snapshot:

    def __init__(self, file_name) -> None:
        self.file_name = file_name

    def take_snapshot(self, data: list) -> None:
        with open(self.file_name, 'w') as f:
            for line in data:
                if '\n' in line:
                    f.write(str(line))
                else:
                    f.write(str(line) + '\n')

    def retrieve(self) -> list:
        with open(self.file_name, 'r') as f:
            return f.readlines()
    
    def clear(self) -> None:
        with open(self.file_name, 'w') as f:
            f.write('')


@app.command()
def add() -> None:
    savestate = Snapshot(path)
    lst_tasks = []

    while True:
        task = input("Add a task [q to quit]: ")
        if task.lower() == 'q':
            break
        else:
            lst_tasks.append(task.capitalize())
   
    savestate.take_snapshot(lst_tasks)
    print("Tasks Saved")


@app.command()
def check() -> None:
    savestate = Snapshot(path)    

    print("\nYour Tasks: \n")
    for index, task in enumerate(savestate.retrieve()):
        print(f"Task {index + 1}: {task[0:-1]}\n")
    
    print('\n')


@app.command()
def rem(index: int) -> None:
    savestate = Snapshot(path)
    tasks = savestate.retrieve()

    try:
        tasks.pop(index - 1)
        savestate.take_snapshot(tasks) 

    except IndexError:
        print("Out of bounds")


@app.command()
def dellall() -> None:
    savestate = Snapshot(path)
    savestate.clear()


if __name__ == '__main__':
    app()
